<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
  xmlns:wsp="http://www.w3.org/ns/ws-policy"
  xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="http://example.com/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://example.com/" name="ShopInfoService">
  <types/>
  <message name="getShopInfo">
    <part name="arg0" type="xsd:string"/>
  </message>
  <message name="getShopInfoResponse">
    <part name="return" type="xsd:string"/>
  </message>
  <portType name="ShopInfo">
    <operation name="getShopInfo">
      <input wsam:Action="http://example.com/ShopInfo/getShopInfoRequest" message="tns:getShopInfo"/>
      <output wsam:Action="http://example.com/ShopInfo/getShopInfoResponse" message="tns:getShopInfoResponse"/>
    </operation>
  </portType>
  <binding name="ShopInfoPortBinding" type="tns:ShopInfo">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <operation name="getShopInfo">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" namespace="http://example.com/"/>
      </input>
      <output>
        <soap:body use="literal" namespace="http://example.com/"/>
      </output>
    </operation>
  </binding>
  <service name="ShopInfoService">
    <port name="ShopInfoPort" binding="tns:ShopInfoPortBinding">
      <soap:address location="http://localhost:8080/TestMart/ShopInfoService"/>
    </port>
  </service>
</definitions>